server:
  port: ${CUSTOM.SERVER.PORT:5010}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_db
    username: debuggeandoideas
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
     ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         format_sql: tru